import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,place,overlaps} from '../src/layout.js';
import {AudioEngine} from '../src/audio.js';
function fixture(){const e=new AudioEngine();const sources=[];e.ctx={currentTime:10,createBufferSource(){const source={connect(){},disconnect(){},start(...args){this.startArgs=args},stop(){this.onended?.()}};sources.push(source);return source}};e.init=async()=>{};e.mix={gain:{setValueAtTime(){}}};e.output={};e.buffer={duration:30};e.duration=30;e.fileName='fixture.wav';e.stream={getTracks:()=>[]};return {e,sources}}
test('moving a module resolves overlap without hiding neighbors',()=>{const result=place(defaults,'wave',{x:3,y:0});for(let i=0;i<result.length;i++)for(let j=i+1;j<result.length;j++)assert.equal(overlaps(result[i],result[j]),false);assert.equal(result.length,defaults.length);assert.equal(result.find(x=>x.id==='wave').x,3)});
test('resizing clamps geometry and adding hidden module remains collision-free',()=>{let result=place(defaults,'surface',{w:99,x:20,h:-3});result=place(result,'status',{hidden:false});assert.equal(result.find(x=>x.id==='surface').w,12);for(let i=0;i<result.length;i++)for(let j=i+1;j<result.length;j++)assert.equal(overlaps(result[i],result[j]),false)});
test('pause and resume keep exact position and microphone active',async()=>{const {e,sources}=fixture();let ended=0;e.onEnd=()=>ended++;e.startFile();e.ctx.currentTime=14.5;e.pause();assert.equal(e.position,4.5);assert.ok(e.stream);assert.equal(e.active,true);assert.equal(ended,0);await e.resume();assert.deepEqual(sources.at(-1).startArgs,[0,4.5]);e.ctx.currentTime=15.5;assert.equal(e.position,5.5)});
test('seeking while paused does not play; natural end fires only once for active source',async()=>{const {e,sources}=fixture();let ended=0;e.onEnd=()=>ended++;e.seek(12);assert.equal(e.fileSource,null);assert.equal(e.position,12);await e.resume();const old=sources.at(-1);e.seek(20);old.onended();assert.equal(ended,0);sources.at(-1).onended();assert.equal(ended,1);assert.equal(e.position,30);await e.resume();assert.deepEqual(sources.at(-1).startArgs,[0,0])});
