import React,{useEffect,useRef,useState} from 'react';
import {ArrowsOut,ArrowsIn,SlidersHorizontal,DotsSix,Resize,X} from '@phosphor-icons/react';
import {defaults,place,loadLayout} from './layout';
export function ModuleBoard({modules}){
 const [layout,setLayout]=useState(loadLayout),[edit,setEdit]=useState(false),[max,setMax]=useState(null),[selected,setSelected]=useState(null);const board=useRef(),dialog=useRef();
 useEffect(()=>{try{localStorage.setItem('blackmamba-layout-v1',JSON.stringify(layout))}catch{}},[layout]);
 const rows=Math.max(13,...layout.filter(x=>!x.hidden).map(x=>x.y+x.h));
 const change=(id,patch)=>setLayout(old=>place(old,id,patch));const settings=id=>{setSelected(id);dialog.current.showModal();};const cell=layout.find(x=>x.id===selected),module=modules.find(x=>x.id===selected);
 const moveModule=(e,id)=>{if(!edit||max)return;e.preventDefault();const initial=layout.find(x=>x.id===id),original=layout,bounds=board.current.getBoundingClientRect(),start=[e.clientX,e.clientY],target=e.currentTarget;target.setPointerCapture(e.pointerId);const move=ev=>setLayout(place(original,id,{x:initial.x+Math.round((ev.clientX-start[0])/(bounds.width/12)),y:initial.y+Math.round((ev.clientY-start[1])/(bounds.height/rows))}));const end=()=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',end);target.removeEventListener('pointercancel',end)};target.addEventListener('pointermove',move);target.addEventListener('pointerup',end);target.addEventListener('pointercancel',end);};
 const resize=e=>{const id=e.currentTarget.dataset.id,initial=layout.find(x=>x.id===id),original=layout,bounds=board.current.getBoundingClientRect(),start=[e.clientX,e.clientY],target=e.currentTarget;target.setPointerCapture(e.pointerId);const move=ev=>setLayout(place(original,id,{w:initial.w+Math.round((ev.clientX-start[0])/(bounds.width/12)),h:initial.h+Math.round((ev.clientY-start[1])/(bounds.height/rows))}));const end=()=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',end);target.removeEventListener('pointercancel',end);};target.addEventListener('pointermove',move);target.addEventListener('pointerup',end);target.addEventListener('pointercancel',end);};
 return <><div className="workspace-tools"><strong>Laboratorio</strong><span className="workspace-hint">{edit?'Arrastra la cabecera o la esquina de cada módulo':'Audio, mediciones y voz en un mismo espacio'}</span><button aria-pressed={edit} onClick={()=>setEdit(!edit)}>{edit?'Terminar organización':'Organizar módulos'}</button><details className="module-menu"><summary>Módulos</summary><div>{modules.map(m=><label key={m.id}><input type="checkbox" checked={!layout.find(x=>x.id===m.id)?.hidden} onChange={e=>change(m.id,{hidden:!e.target.checked})}/>{m.title}</label>)}<button onClick={()=>{setLayout(defaults);setMax(null)}}>Restablecer distribución</button></div></details></div>
 <div className={'module-board '+(edit?'editing ':'')+(max?'has-max':'')} ref={board} style={{'--rows':rows}} onDragOver={e=>{if(edit)e.preventDefault()}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/blackmamba-module');if(!layout.some(x=>x.id===id))return;const r=board.current.getBoundingClientRect();change(id,{x:Math.floor((e.clientX-r.left)/r.width*12),y:Math.floor((e.clientY-r.top)/r.height*rows)});}}>
 {layout.map(cell=>{const m=modules.find(x=>x.id===cell.id);if(!m)return null;return <section key={cell.id} data-module={cell.id} className={'panel module '+(cell.id==='surface'?'surface ':'')+(max===cell.id?'maximized':'')} style={{gridColumn:`${cell.x+1} / span ${cell.w}`,gridRow:`${cell.y+1} / span ${cell.h}`,display:cell.hidden||max&&max!==cell.id?'none':undefined}}><div className="module-heading"><h2 data-draggable={edit} onPointerDown={e=>moveModule(e,cell.id)}>{edit&&<DotsSix size={16}/>} {m.title}</h2><div className="module-actions"><button title={'Ajustar '+m.title} aria-label={'Ajustar '+m.title} onClick={()=>settings(cell.id)}><SlidersHorizontal/></button><button title={max?'Restaurar módulo':'Ampliar '+m.title} aria-label={max?'Restaurar módulo':'Ampliar '+m.title} onClick={()=>setMax(max?null:cell.id)}>{max?<ArrowsIn/>:<ArrowsOut/>}</button>{edit&&<button aria-label={'Ocultar '+m.title} onClick={()=>change(cell.id,{hidden:true})}><X/></button>}</div></div><div className="module-content">{m.content}</div>{edit&&!max&&<button data-id={cell.id} className="resize-handle" aria-label={'Redimensionar '+m.title} onPointerDown={resize} onClick={e=>{if(e.detail===0)settings(cell.id)}}><Resize size={15}/></button>}</section>})}
 </div><dialog ref={dialog} className="module-dialog"><div className="dialog-header"><h2>{module?.title}</h2><button onClick={()=>dialog.current.close()}>Cerrar</button></div>{cell&&<><fieldset><legend>Posición y tamaño</legend><div className="field-grid">{[['x','Columna',0,10],['y','Fila',0,100],['w','Ancho',2,12],['h','Alto',3,16]].map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} value={cell[key]} onChange={e=>change(cell.id,{[key]:Number(e.target.value)})}/></label>)}</div><p className="hint">Los módulos vecinos se desplazan para evitar superposición.</p></fieldset>{module?.settings||<p className="hint">Los controles de este módulo están en su panel.</p>}</>}</dialog></>;
}
