import React,{useEffect,useRef} from 'react';
export const plotDefaults={color:'#348aff',palette:'spectrum',width:1,gain:1,yaw:-35,pitch:32,zoom:1,rotate:false,frozen:false};
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
export function PlotSettings({type,options,setOptions}){const set=(key,value)=>setOptions({...options,[key]:value,...(key==='color'&&!['wave','pitch','phase'].includes(type)?{palette:'custom'}:{})});return <fieldset><legend>Visualización</legend><div className="field-grid"><label>Color de trazo<input type="color" value={options.color} onChange={e=>set('color',e.target.value)}/></label>{!['wave','pitch','phase'].includes(type)&&<label>Paleta<select value={options.palette} onChange={e=>set('palette',e.target.value)}><option value="spectrum">Espectral</option><option value="ice">Hielo</option><option value="fire">Fuego</option><option value="custom">Color elegido</option></select></label>}{type!=='spectrogram'&&<label>Grosor · {options.width}px<input type="range" min="0.3" max="4" step="0.1" value={options.width} onChange={e=>set('width',+e.target.value)}/></label>}{type!=='pitch'&&<label>Escala visual · {options.gain}×<input type="range" min="0.25" max="2" step="0.05" value={options.gain} onChange={e=>set('gain',+e.target.value)}/></label>}{type==='surface'&&<>{[['yaw','Ángulo horizontal',-180,180],['pitch','Elevación',10,80],['zoom','Zoom',.5,1.8]].map(([key,label,min,max])=><label key={key}>{label} · {options[key]}<input type="range" min={min} max={max} step={key==='zoom'?.05:1} value={options[key]} onChange={e=>set(key,+e.target.value)}/></label>)}<label className="check-field"><input type="checkbox" checked={options.rotate} onChange={e=>set('rotate',e.target.checked)}/>Rotación automática</label></>}<label className="check-field"><input type="checkbox" checked={options.frozen} onChange={e=>set('frozen',e.target.checked)}/>Congelar visual</label></div><button onClick={()=>setOptions({...plotDefaults})}>Restablecer visual</button></fieldset>}
export function Plot({engine,type,tick,options=plotDefaults,setOptions}){
 const ref=useRef(),drag=useRef(),snapshot=useRef(),optionsRef=useRef(options);optionsRef.current=options;
 useEffect(()=>{if(type!=='surface')return;const el=ref.current;const wheel=e=>{e.preventDefault();const o=optionsRef.current;setOptions({...o,zoom:Math.round(clamp(o.zoom-e.deltaY*.001,.5,1.8)*100)/100})};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[type,setOptions]);
 useEffect(()=>{
  const canvas=ref.current,w=canvas.clientWidth,h=canvas.clientHeight;if(w<2||h<2)return;const ratio=Math.min(devicePixelRatio,2);canvas.width=w*ratio;canvas.height=h*ratio;const c=canvas.getContext('2d');c.scale(ratio,ratio);
  if(options.frozen&&!snapshot.current)snapshot.current={active:engine.active,wave:engine.wave?.slice(),freq:engine.freq?.slice(),left:engine.left?.slice(),right:engine.right?.slice(),history:engine.history.map(x=>x.slice()),pitchHistory:engine.pitchHistory.slice()};if(!options.frozen)snapshot.current=null;const data=snapshot.current||engine;
  const css=getComputedStyle(document.documentElement),ink=css.getPropertyValue('--plot-label').trim(),grid=css.getPropertyValue('--grid').trim();
  const color=t=>options.palette==='custom'?`color-mix(in srgb, ${options.color} ${15+clamp(t,0,1)*85}%, #101522)`:options.palette==='ice'?`hsl(${220-t*45},85%,${25+t*48}%)`:options.palette==='fire'?`hsl(${t*55},95%,${20+t*40}%)`:`hsl(${260-clamp(t,0,1)*260},95%,52%)`;
  const path=(points,col=options.color,width=options.width)=>{c.strokeStyle=col;c.lineWidth=width;c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.stroke()};
  c.font='10px system-ui';c.fillStyle=ink;
  if(type!=='surface'){for(let x=0;x<w;x+=w/12)path([[x,0],[x,h]],grid,.5);for(let y=0;y<h;y+=h/6)path([[0,y],[w,y]],grid,.5);}
  const amplitude=v=>clamp((v+100)/100*options.gain,0,1);
  if(type==='surface'){
   const motion=options.rotate&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&!options.frozen?tick*.25:0;
   const yaw=(options.yaw+motion)*Math.PI/180,pitch=options.pitch*Math.PI/180,scale=Math.min(w*.8,h*.82)*options.zoom;
   const project=(x,y,z)=>{x-=.5;y-=.5;const rx=x*Math.cos(yaw)-y*Math.sin(yaw),ry=x*Math.sin(yaw)+y*Math.cos(yaw);return [w*.49+rx*scale,h*.63+(ry*Math.sin(pitch)-z*.8*Math.cos(pitch))*scale,ry*Math.cos(pitch)+z*Math.sin(pitch)];};
   for(let i=0;i<=5;i++){const t=i/5;path([project(t,0,0),project(t,1,0)],grid,.7);path([project(0,t,0),project(1,t,0)],grid,.7);path([project(0,1,t),project(1,1,t)],grid,.7);path([project(t,1,0),project(t,1,1)],grid,.7);}
   path([project(0,0,1),project(0,0,0),project(1,0,0),project(1,1,0)],ink,.8);
   const rows=data.history,faces=[];
   const z=(j,i)=>amplitude((rows[j][Math.max(0,i-1)]+rows[j][i]+rows[j][Math.min(71,i+1)])/3);
   for(let j=0;j<rows.length-2;j+=2)for(let i=0;i<70;i+=2){const values=[z(j,i),z(j,i+2),z(j+2,i+2),z(j+2,i)];const points=[project(i/71,j/64,values[0]),project((i+2)/71,j/64,values[1]),project((i+2)/71,(j+2)/64,values[2]),project(i/71,(j+2)/64,values[3])];faces.push({points,value:values.reduce((a,b)=>a+b)/4,depth:points.reduce((a,p)=>a+p[2],0)/4});}
   faces.sort((a,b)=>a.depth-b.depth);for(const f of faces){c.beginPath();f.points.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.closePath();c.fillStyle=color(f.value);c.globalAlpha=options.palette==='custom'?.3+f.value*.7:.9;c.fill();c.globalAlpha=1;c.strokeStyle=options.palette==='custom'?options.color:'#ffffff65';c.lineWidth=options.width*.45;c.stroke();}
   c.fillStyle=ink;c.textAlign='center';const label=(text,x,y,z,dy=15)=>{const p=project(x,y,z);c.fillText(text,p[0],p[1]+dy)};
   label('30 Hz',0,0,0);label('20 kHz',1,0,0);label('Frecuencia (Hz)',.5,0,0,29);label('Tiempo →',1,.6,0);label('0 dB',0,0,1,-7);label('−100 dB',0,0,0,-7);
   const legend=c.createLinearGradient(0,h*.22,0,h*.65);for(let i=0;i<=10;i++)legend.addColorStop(i/10,color(1-i/10));c.fillStyle=legend;c.fillRect(w-16,h*.22,7,h*.43);c.fillStyle=ink;c.textAlign='right';c.fillText('Alta',w-7,h*.22-7);c.fillText('Baja',w-7,h*.65+14);
  }
  if(!data.active&&!data.history.length){c.fillStyle=ink;c.textAlign='center';c.fillText('Esperando señal de audio',w/2,h/2);return;}
  if(type==='phase'&&data.left&&data.right){const points=[];for(let i=0;i<1024;i+=2)points.push([w/2+(data.left[i]-data.right[i])*w*.3*options.gain,h/2-(data.left[i]+data.right[i])*h*.3*options.gain]);path(points);c.fillStyle=ink;c.textAlign='left';c.fillText('L',8,15);c.textAlign='right';c.fillText('R',w-8,15);}
  if(type==='wave'&&data.wave)path(Array.from({length:Math.floor(w)},(_,i)=>[i,h/2+data.wave[Math.floor(i/w*2048)]*h*.44*options.gain]));
  if(type==='fft'){const b=data.history.at(-1)||[];b.forEach((v,i)=>{const z=amplitude(v);c.fillStyle=color(1-i/b.length);c.fillRect(i*w/b.length,h-z*h,Math.max(1,w/b.length*clamp(options.width/2,.15,1)),z*h)})}
  if(type==='spectrogram')data.history.forEach((row,x)=>row.forEach((v,y)=>{c.fillStyle=color(amplitude(v));c.fillRect(x*w/65,h-(y+1)*h/72,w/65+1,h/72+1)}));
  if(type==='pitch'){let segment=[];for(let i=0;i<data.pitchHistory.length;i++){const f=data.pitchHistory[i];if(f)segment.push([i*w/160,h-Math.log2(f/55)/5*h]);else{path(segment);segment=[]}}path(segment)}
  if(type==='harmonics'){const hz=data.pitchHistory.at(-1);if(hz)for(let i=1;i<=12;i++){const k=Math.round(hz*i*8192/engine.ctx.sampleRate),v=data.freq[k]??-100,x=i*w/13,y=h-amplitude(v)*h;path([[x,h],[x,y]],color(1-i/13));c.fillStyle=color(1-i/13);c.beginPath();c.arc(x,y,2+options.width,0,Math.PI*2);c.fill()}}
 },[tick,type,options,engine]);
 const orbit=e=>{if(type!=='surface')return;drag.current={x:e.clientX,y:e.clientY,yaw:options.yaw,pitch:options.pitch};e.currentTarget.setPointerCapture(e.pointerId)};
 return <canvas ref={ref} className={type==='surface'?'orbit-canvas':''} aria-label={type==='surface'?'Superficie 3D: arrastra para girar, rueda para acercar':type} tabIndex={type==='surface'?0:undefined} onPointerDown={orbit} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} onPointerMove={e=>{if(!drag.current)return;setOptions({...options,rotate:false,yaw:Math.round(((drag.current.yaw+(e.clientX-drag.current.x)*.5+540)%360)-180),pitch:Math.round(clamp(drag.current.pitch+(e.clientY-drag.current.y)*.3,10,80))})}} onKeyDown={e=>{if(type!=='surface')return;const keys={ArrowLeft:['yaw',-5],ArrowRight:['yaw',5],ArrowUp:['pitch',5],ArrowDown:['pitch',-5]};if(keys[e.key]){e.preventDefault();const [key,delta]=keys[e.key];setOptions({...options,rotate:false,[key]:clamp(options[key]+delta,key==='pitch'?10:-180,key==='pitch'?80:180)})}}}/>;
}
