import React,{useEffect,useRef,useState} from 'react';
import {encodeWav} from './speech';
const bridge=window.blackmambaSpeech;
const translations={'Speech':'Voz','Music':'Música','Silence':'Silencio','Male speech, man speaking':'Voz masculina','Female speech, woman speaking':'Voz femenina','Conversation':'Conversación','Narration, monologue':'Narración','Singing':'Canto','Dog':'Perro','Bark':'Ladrido','Cat':'Gato','Meow':'Maullido','Bird':'Ave','Bird vocalization, bird call, bird song':'Canto de ave','Applause':'Aplausos','Clapping':'Palmadas','Laughter':'Risa','Vehicle':'Vehículo','Car':'Automóvil','Engine':'Motor','Rain':'Lluvia','Water':'Agua','Wind':'Viento','Keyboard (musical)':'Teclado musical','Piano':'Piano','Guitar':'Guitarra','Drum':'Tambor','Drum kit':'Batería','Door':'Puerta','Knock':'Golpe en puerta','Bell':'Campana','Telephone bell ringing':'Teléfono','Alarm':'Alarma','Siren':'Sirena','Noise':'Ruido','Animal':'Animal'};
function restoreFeedback(){try{return JSON.parse(localStorage.getItem('blackmamba-sound-reviews')||'[]').slice(-200)}catch{return []}}
export function SpeechPanel({engine,active}){
 const [enabled,setEnabled]=useState(true),[language,setLanguage]=useState('auto'),[state,setState]=useState(bridge?'Whisper local listo · esperando voz':'Disponible en la aplicación Mac'),[rows,setRows]=useState([]),[sound,setSound]=useState(null),[soundState,setSoundState]=useState('Esperando un sonido'),[reviews,setReviews]=useState(restoreFeedback),[correction,setCorrection]=useState(''),[correcting,setCorrecting]=useState(false),[storageError,setStorageError]=useState('');
 const options=useRef({enabled,language});options.current={enabled,language};
 const generation=useRef(0),queue=useRef([]),running=useRef(false),soundBusy=useRef(false),alive=useRef(false),transcriptRef=useRef();
 useEffect(()=>{alive.current=true;if(!bridge)return()=>{alive.current=false};
  bridge.status().then(s=>{if(alive.current&&!s.available)setState(s.model)}).catch(()=>setState('No se pudo iniciar Whisper'));
  async function drain(){if(running.current)return;running.current=true;
   while(queue.current.length&&alive.current){const task=queue.current.shift();if(task.generation!==generation.current)continue;setState('Reconociendo palabras · '+(queue.current.length?`${queue.current.length} fragmentos en espera`:'local'));
    try{const result=await bridge.transcribe(task.wav,task.language);if(alive.current&&task.generation===generation.current){if(result.text)setRows(old=>[...old,{id:crypto.randomUUID(),text:result.text,time:task.time,source:task.source}]);setState(result.text?'Escuchando · texto actualizado':'Escuchando · sin palabras claras');}}
    catch(e){if(alive.current&&task.generation===generation.current)setState('No se pudo transcribir este fragmento. '+e.message.replace(/^Error invoking remote method[^:]+:/,''));}
   }running.current=false;
  }
  engine.onSpeech=chunk=>{
   if(!options.current.enabled||!alive.current)return;
   const wav=encodeWav(chunk.audio,chunk.rate),epoch=generation.current,time=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
   if(queue.current.length<4){queue.current.push({wav,language:options.current.language,generation:epoch,time,source:chunk.source});drain();}
   else setState('El equipo no alcanza el ritmo: se omitió un fragmento. Detén el audio para terminar la cola.');
   if(!soundBusy.current){soundBusy.current=true;setSoundState('Analizando sonido…');bridge.classify(wav).then(tags=>{if(alive.current&&epoch===generation.current){const top=tags[0];setSound(old=>old&&!old.review?old:(top&&top.score>=.12?{...top,id:crypto.randomUUID(),time,source:chunk.source}:null));setSoundState(top&&top.score>=.12?'Sugerencia por confirmar':'Sonido no identificado');}}).catch(()=>{if(alive.current)setSoundState('Clasificador no disponible; la transcripción continúa')}).finally(()=>{soundBusy.current=false});}
  };
  return()=>{alive.current=false;engine.onSpeech=null;queue.current=[];generation.current++;bridge.cancel().catch(()=>{});};
 },[engine]);
 useEffect(()=>{if(transcriptRef.current)transcriptRef.current.scrollTop=transcriptRef.current.scrollHeight},[rows]);
 function clear(){generation.current++;queue.current=[];bridge?.cancel().catch(()=>{});setRows([]);setSound(null);setState('Transcripción vacía · esperando voz');}
 function review(decision){if(!sound)return;const value={...sound,decision,correction:decision==='corrected'?correction.trim():null,reviewedAt:new Date().toISOString()};if(decision==='corrected'&&!value.correction)return;const next=[...reviews,value].slice(-200);setReviews(next);try{localStorage.setItem('blackmamba-sound-reviews',JSON.stringify(next));setStorageError('');}catch{setStorageError('No se pudieron guardar las revisiones en este equipo.');}setSound({...sound,review:decision,correction:value.correction});setCorrecting(false);setCorrection('');}
 function download(){const blob=new Blob([rows.map(r=>`[${r.time}] ${r.text}`).join('\n')],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='BlackMamba-transcripcion.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 return <section className="speech-panel panel"><div className="speech-heading"><div><h2>Palabras en vivo <span className="whisper-badge">WHISPER LOCAL</span></h2><p>English + Español · aparece texto al hacer una pausa o cada 8 segundos</p></div><div className="speech-controls"><label><input type="checkbox" checked={enabled} disabled={!bridge} onChange={e=>{setEnabled(e.target.checked);if(!e.target.checked){generation.current++;queue.current=[];bridge?.cancel().catch(()=>{});setState('Transcripción pausada');}else setState('Escuchando · esperando voz')}}/> Transcribir</label><select aria-label="Idioma de transcripción" value={language} onChange={e=>setLanguage(e.target.value)}><option value="auto">Automático · EN / ES</option><option value="es">Español</option><option value="en">English</option></select><button disabled={!rows.length} onClick={download}>Guardar texto</button><button disabled={!rows.length} onClick={clear}>Limpiar</button></div></div><div className="speech-body"><div><div className="speech-status" role="status"><i className={active&&enabled?'on':''}/>{!enabled?'Transcripción pausada':state}</div><div className="transcript" ref={transcriptRef} aria-live="polite" aria-label="Transcripción">{rows.length?rows.map(r=><p key={r.id}><time>{r.time}</time>{r.text}</p>):<p className="transcript-empty">{bridge?'Habla en inglés o español. Tus palabras aparecerán aquí mientras continúan los visuales.':'Abre la aplicación Mac para transcribir con Whisper local.'}</p>}</div></div><aside className="sound-review"><h3>Sonidos · tú confirmas</h3><p className="hint">{soundState}</p>{sound?<><strong>{translations[sound.label]||sound.label}</strong><small>{sound.label} · puntuación {(sound.score*100).toFixed(0)}%</small>{sound.review?<p className="hint">{sound.review==='yes'?'Confirmado':sound.review==='no'?'Rechazado':`Corregido: ${sound.correction}`}</p>:<div className="review-actions"><button onClick={()=>review('yes')}>Sí</button><button onClick={()=>review('no')}>No</button><button onClick={()=>setCorrecting(true)}>Corregir</button></div>}{correcting&&<form onSubmit={e=>{e.preventDefault();review('corrected')}}><input aria-label="Etiqueta correcta" placeholder="¿Qué sonido es?" value={correction} maxLength={100} onChange={e=>setCorrection(e.target.value)}/><button disabled={!correction.trim()}>Guardar</button></form>}</>:<p className="hint">Las etiquetas aparecerán con el audio.</p>}<p className="hint">{reviews.length} revisiones guardadas en este Mac. Tus correcciones se registran; no reentrenan el modelo automáticamente.</p>{storageError&&<p role="alert">{storageError}</p>}</aside></div></section>;
}
